# Generated by Django 2.1 on 2018-10-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
