# Generated by Django 2.1.2 on 2018-12-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_purchaseditem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='returneditem',
            name='condition',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
