# Generated by Django 2.1 on 2018-12-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_purchaseditem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='returneditem',
            name='condition',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
