# Generated by Django 2.1 on 2018-12-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_returneditem_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returneditem',
            name='condition',
            field=models.CharField(max_length=10),
        ),
    ]
