# Generated by Django 2.1 on 2018-12-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20181212_0655'),
        ('transaction', '0005_auto_20181215_0141'),
    ]

    operations = [
    ]
