# Generated by Django 2.1 on 2019-01-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_remove_returneditem_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='returneditem',
            name='condition',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
