# Generated by Django 2.1 on 2019-01-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Entry Date')),
            ],
        ),
    ]
